USE [master]
GO

IF NOT EXISTS (
	SELECT name FROM master.dbo.sysdatabases 
	WHERE name = N'CSOFT_PHONEBOOK')
BEGIN
	CREATE DATABASE [CSOFT_PHONEBOOK] 
		ON PRIMARY
		(
			NAME = N'CSOFT_PHONEBOOK', 
			FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CSOFT_PHONEBOOK.mdf' , 
			SIZE = 16MB , 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64MB
		)
		LOG ON 
		(
			NAME = N'CSOFT_PHONEBOOK_log', 
			FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CSOFT_PHONEBOOK_log.ldf' , 
			SIZE = 16MB , 
			MAXSIZE = UNLIMITED , 
			FILEGROWTH = 64MB
		)
END