USE [CSOFT_PHONEBOOK]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PHONE_NUMBERS]') AND type = 'U' )
	DROP TABLE [PHONE_NUMBERS]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PERSONS]') AND type = 'U' )
	DROP TABLE [PERSONS]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PHONE_TYPES]') AND type = 'U' )
	DROP TABLE [PHONE_TYPES]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CITIES]') AND type = 'U' )
	DROP TABLE [CITIES]
GO

/**
Таблица за градове (CITIES)
o Уникален идентификатор (ID)
o Версия на ред (UPDATE_COUNTER)
o Име на град
o Област
**/
CREATE TABLE [CITIES]
(
	[ID] INT IDENTITY(1,1),
	[UPDATE_COUNTER] INT NOT NULL DEFAULT 0,
	[NAME] NVARCHAR(32) NOT NULL,
	[REGION] NVARCHAR(32) NOT NULL,

	CONSTRAINT PK_CITIES_ID PRIMARY KEY (ID)
)

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_CITIES_NAME_REGION' AND object_id = OBJECT_ID('CITIES'))
BEGIN
	CREATE INDEX [IX_CITIES_NAME_REGION] 
	ON CITIES ([NAME], [REGION])
END

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_CITIES_NAME' AND object_id = OBJECT_ID('CITIES'))
BEGIN
	CREATE INDEX [IX_CITIES_NAME] 
	ON CITIES ([NAME])
END
GO

/**
Таблица с типове телефони – mobile, home, work (PHONE_TYPES)
o Уникален идентификатор (ID)
o Версия на ред (UPDATE_COUNTER)
o Тип телефон
**/
CREATE TABLE [PHONE_TYPES]
(
	[ID] INT IDENTITY(1,1),
	[UPDATE_COUNTER] INT NOT NULL DEFAULT 0,
	[TYPE] NVARCHAR(32) NOT NULL,

	CONSTRAINT PK_PHONE_TYPES_ID PRIMARY KEY (ID)
)
GO

/**
Таблица с абонати (PERSONS)
o Уникален идентификатор (ID)
o Версия на ред (UPDATE_COUNTER)
o Име
o Презиме
o Фамилия
o ЕГН
o ID на град
o Адрес
**/
CREATE TABLE [PERSONS]
(
	[ID] INT IDENTITY(1,1),
	[UPDATE_COUNTER] INT NOT NULL DEFAULT 0,
	[FIRST_NAME] NVARCHAR(64) NOT NULL,
	[MIDDLE_NAME] NVARCHAR(64) NOT NULL,
	[LAST_NAME] NVARCHAR(64) NOT NULL,
	[UCN] NVARCHAR(16) NOT NULL,
	[CITY_ID] INT NOT NULL,
	[ADDRESS] NVARCHAR(128) NOT NULL

	CONSTRAINT PK_PERSONS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PERSONS_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITIES(ID),
	CONSTRAINT UX_PERSONS_UCN UNIQUE (UCN)
)

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_PERSONS_CITY_ID' AND object_id = OBJECT_ID('PERSONS'))
BEGIN
	CREATE INDEX [IX_PERSONS_CITY_ID] 
	ON PERSONS ([CITY_ID])
END
GO

/**
Таблица с телефонни номера на абонати (PHONE_NUMBERS)
o Уникален идентификатор (ID)
o Версия на ред (UPDATE_COUNTER)
o ID на абонат
o ID на тип телефон
o Телефон
**/
CREATE TABLE [PHONE_NUMBERS]
(
	[ID] INT IDENTITY(1,1),
	[UPDATE_COUNTER] INT NOT NULL DEFAULT 0,
	[PERSON_ID] INT NOT NULL,
	[PHONE_TYPE_ID] INT NOT NULL,
	[PHONE] NVARCHAR(32) NOT NULL

	CONSTRAINT PK_PHONE_NUMBERS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PHONE_NUMBERS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(ID),
	CONSTRAINT FK_PHONE_NUMBERS_PHONE_TYPE_ID FOREIGN KEY (PHONE_TYPE_ID) REFERENCES PHONE_TYPES(ID),
)

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_PHONE_NUMBERS_PERSON_ID' AND object_id = OBJECT_ID('PHONE_NUMBERS'))
BEGIN
	CREATE INDEX [IX_PHONE_NUMBERS_PERSON_ID] 
	ON PHONE_NUMBERS ([PERSON_ID])
END

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_PHONE_NUMBERS_PHONE_TYPE_ID' AND object_id = OBJECT_ID('PHONE_NUMBERS'))
BEGIN
	CREATE INDEX [IX_PHONE_NUMBERS_PHONE_TYPE_ID] 
	ON PHONE_NUMBERS ([PHONE_TYPE_ID])
END
GO