USE [CSOFT_PHONEBOOK]
GO

/**
Проверка за наличие на информация в таблиците и премахване ако съществува такава
**/
BEGIN TRANSACTION
BEGIN TRY

	IF EXISTS (SELECT * FROM [PHONE_NUMBERS])
	BEGIN
		DELETE FROM [PHONE_NUMBERS]
	END
	IF EXISTS (SELECT * FROM [PERSONS])
	BEGIN
		DELETE FROM [PERSONS]
	END
	IF EXISTS (SELECT * FROM [PHONE_TYPES])
	BEGIN
		DELETE FROM [PHONE_TYPES]
	END
	IF EXISTS (SELECT * FROM [CITIES])
	BEGIN
		DELETE FROM [CITIES]
	END

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на основна информация в БД: градове, типове телефони
**/
BEGIN TRANSACTION
BEGIN TRY
	/**
	Добавяне на градове и техните региони
	**/
	INSERT INTO [CITIES]
		([NAME], [REGION])
	VALUES 
		('VARNA', 'VARNA'),
		('VETRINO', 'VARNA'),
		('SUVOROVO', 'VARNA'),
		('KARNOBAT', 'BURGAS'),
		('SOZOPOL', 'BURGAS'),
		('ELENA', 'VELIKO TARNOVO'), 
		('PAVLIKENI', 'VELIKO TARNOVO')

	/**
	Добавяне на типове телефони
	**/
	INSERT INTO [PHONE_TYPES]
		([TYPE])
	VALUES 
		('HOME'), 
		('MOBILE'),
		('WORK')

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на контакт
**/
BEGIN TRANSACTION
BEGIN TRY

	INSERT INTO [PERSONS]
		([FIRST_NAME],[MIDDLE_NAME],[LAST_NAME],[UCN],[CITY_ID],[ADDRESS])
	VALUES 
		('John', 'Smith', 'Smith', '6315345891', (SELECT ID FROM [CITIES] WHERE [NAME] = 'SUVOROVO'), 'ul. Valev 34')

	DECLARE @PERSON_ID INT = @@IDENTITY

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID], [PHONE], [PHONE_TYPE_ID])
	VALUES 
		(@PERSON_ID, '+35911111111', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE')),
		(@PERSON_ID, '052456235', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'HOME'))

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на контакт
**/
BEGIN TRANSACTION
BEGIN TRY

	INSERT INTO [PERSONS]
		([FIRST_NAME],[MIDDLE_NAME],[LAST_NAME],[UCN],[CITY_ID],[ADDRESS])
	VALUES 
		('Rose', 'Smith', 'Smith', '6315323561', (SELECT ID FROM [CITIES] WHERE [NAME] = 'SUVOROVO'), 'ul. Valev 34')

	DECLARE @PERSON_ID INT = @@IDENTITY

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID], [PHONE], [PHONE_TYPE_ID])
	VALUES 
		(@PERSON_ID, '052153242', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'HOME'))

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на контакт
**/
BEGIN TRANSACTION
BEGIN TRY

	INSERT INTO [PERSONS]
		([FIRST_NAME],[MIDDLE_NAME],[LAST_NAME],[UCN],[CITY_ID],[ADDRESS])
	VALUES 
		('Ivan', 'Petrov', 'Ivanov', '5184354812', (SELECT ID FROM [CITIES] WHERE [NAME] = 'SOZOPOL'), 'ul. Vladislav 6')

	DECLARE @PERSON_ID INT = @@IDENTITY

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID], [PHONE], [PHONE_TYPE_ID])
	VALUES 
		(@PERSON_ID, '+35987562542', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE')),
		(@PERSON_ID, '+35987563542', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE')),
		(@PERSON_ID, '+35987564542', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE')),
		(@PERSON_ID, '+35987565542', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE'))

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на контакт
**/
BEGIN TRANSACTION
BEGIN TRY

	INSERT INTO [PERSONS]
		([FIRST_NAME],[MIDDLE_NAME],[LAST_NAME],[UCN],[CITY_ID],[ADDRESS])
	VALUES 
		('Petar', 'Ivanov', 'Petrov', '4215213523', (SELECT ID FROM [CITIES] WHERE [NAME] = 'VARNA'), 'ul. Balkan 2')

	DECLARE @PERSON_ID INT = @@IDENTITY

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID], [PHONE], [PHONE_TYPE_ID])
	VALUES 
		(@PERSON_ID, '+35988964523', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE'))

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Добавяне на контакт
**/
BEGIN TRANSACTION
BEGIN TRY

	INSERT INTO [PERSONS]
		([FIRST_NAME],[MIDDLE_NAME],[LAST_NAME],[UCN],[CITY_ID],[ADDRESS])
	VALUES 
		('Ivanka', 'Ivanova', 'Ivanova', '584113542', (SELECT ID FROM [CITIES] WHERE [NAME] = 'KARNOBAT'), 'ul. Tsvetnitsa 45')

	DECLARE @PERSON_ID INT = @@IDENTITY

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID], [PHONE], [PHONE_TYPE_ID])
	VALUES 
		(@PERSON_ID, '035215253', (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'HOME'))

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION
END CATCH

GO

/**
Промяна на номер на вече съществуващ абонат
**/
UPDATE [PHONE_NUMBERS]
	SET [PHONE] = '+35988456235'
WHERE [PHONE_TYPE_ID] = (SELECT ID FROM [PHONE_TYPES] WHERE [TYPE] = 'MOBILE') AND [PERSON_ID] = (SELECT ID FROM [PERSONS] WHERE [UCN] = '6315345891')
GO